name: ✅ Task
description: Tarefa para implementação de uma User Story
type: "Task"
projects: ["ztrax-ofc/board"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: "Detalhes da tarefa a ser realizada"
      placeholder: "Exemplo: Implementar validação de e-mail no cadastro de usuários"
    validations:
      required: true
