name: 🧾 User Story
description: Criação de funcionalidade
projects: ["ztrax-ofc/board"]
type: "Feature"
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição
      description: |
        ## 🧾 User Story
        
        **COMO** usuário do sistema de rastreamento  
        **QUERO** ser capaz de visualizar todos os pontos no modo presença estando dentro de uma área definida do mapa  
        **PARA** que eu possa saber o local aproximado onde meu ativo se encontra
        
        ---
        
        ## ✅ Critérios de Aceite
        
        - [ ] Aceite item
        
        ---
    validations:
      required: true
